baseURL: "https://n0k0m3.github.io/"
title: n0k0m3 Dev Blog
paginate: 20
theme:
  - hugo-embed-pdf-shortcode
  - PaperMod
enableInlineShortcodes: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: n0k0m3 Dev Blog
  description: "Welcome to n0k0m3 personal website. Here you can find my resume, projects, and Linux guides"
  author: Minh Nguyen
  # author: ["Me", "You"] # multiple authors
  # images: ["/k8s-hexagon.jpeg"]
  keywords: [Blog, Portfolio, PaperMod]
  DateFormat: "January 2, 2006"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true

  defaultTheme: auto # dark, light
  disableThemeToggle: false
  disableSpecial1stPost: false
  disableScrollToTop: false

  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  ShowPostNavLinks: true
  ShowBreadCrumbs: true

  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  comments: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon.ico
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /favicon.ico
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: n0k0m3 Dev Blog
    subtitle: "Driven by insatiable curiosity, I am on a continuous quest to learn and grow, embracing the vast expanse of knowledge that life has to offer"
    imageUrl: /me.png
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Personal Projects
        url: projects
      - name: Resume
        url: resume
      - name: Research
        url: research
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  analytics:
    google:
      SiteVerificationTag: "G-61QY6DPN4Y"
    bing:
      SiteVerificationTag: "642F9756927D2879DC92D9B9EA33A800"
    yandex:
      SiteVerificationTag: "95245003"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    # linkFullImages: true
    # responsiveImages: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  editPost:
    URL: "https://github.com/n0k0m3/n0k0m3.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  socialIcons:
    - name: github
      url: "https://github.com/n0k0m3"
    - name: linkedin
      url: "https://www.linkedin.com/in/minhnguyen251/"

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: about
      name: About Me
      url: /about/
      weight: 30
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

enableGitInfo: true
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - ':git'
    - date
    - publishDate

# Quarto
ignoreFiles:
  - \.qmd$
  - \.ipynb$
  - \.py$
  - \.README.py$